### Identify the intersection between fetal-enriched and disease-enriched TFs

In [6]:
library(tidyverse)

In [11]:
fetal_res <- read.csv("04B_fetal_sig_regulon_df.csv")
fetal_res <- fetal_res %>%
  mutate(regulon = str_extract(regulon, "^[^_]+"))
fetal_res <- fetal_res %>% dplyr::filter(padj < 0.05)

disease_res <- read.csv("04B_disease_sig_regulon_df.csv")
disease_res <- disease_res %>%
  mutate(regulon = str_extract(regulon, "^[^_]+"))
disease_res <- disease_res %>% dplyr::filter(padj < 0.05)

In [12]:
fetal_df <- fetal_res %>%
  select(regulon, cell_type, log2FC_fetal = log2FC)

disease_df <- disease_res %>%
  select(regulon, cell_type, log2FC_disease = log2FC)

In [13]:
shared_regulons <- fetal_df %>%
  inner_join(disease_df, by = c("regulon", "cell_type"))

shared_regulons_dir <- shared_regulons %>%
  filter(sign(log2FC_fetal) == sign(log2FC_disease))

In [14]:
shared_regulons_dir

    regulon cell_type     log2FC_fetal log2FC_disease
1   AR      Cardiomyocyte -1.8722039   -0.06106599
2   EBF3    Cardiomyocyte  0.7311192    0.09819716
3   TCF4    Cardiomyocyte  0.6855273    0.10440702
4   KLF12   Cardiomyocyte  0.3444485    0.06749628
5   ZNF704  Cardiomyocyte  0.4387626    0.03795624
6   ZNF90   Cardiomyocyte  2.1582879    0.41869614
7   RUNX1   Cardiomyocyte  0.3637942    0.02570023
8   ZNF846  Cardiomyocyte  0.7189348    0.17497937
9   BNC2    Cardiomyocyte  0.3827858    0.10150904
10  MLLT10  Cardiomyocyte  0.2833354    0.03239084
11  BACH2   Cardiomyocyte  0.2668514    0.12983196
12  CREM    Cardiomyocyte  0.5709769    0.07914972
13  FLI1    Cardiomyocyte  0.2383953    0.04755126
14  ETV6    Cardiomyocyte  0.2131711    0.03575897
15  EBF1    Cardiomyocyte  0.2332502    0.06439567
16  SMARCC1 Cardiomyocyte  0.3703376    0.06745163
17  IKZF1   Cardiomyocyte  0.2862281    0.05517298
18  ADNP    Cardiomyocyte  0.4067386    0.15302904
19  UBE2K   Cardiomyocyte  0.2758878    0.05445593
20  PLAGL1  Cardiomyocyte  1.1095461    0.78609444
21  NFIX    Cardiomyocyte -1.2734402   -0.27517243
22  PDLIM5  Cardiomyocyte -0.1281074   -0.05691002
23  ZNF423  Cardiomyocyte  0.5825862    0.17400267
24  JUNB    Cardiomyocyte -0.9162258   -0.35494272
25  KDM5A   Cardiomyocyte  0.3659197    0.11004601
26  SPI1    Cardiomyocyte  0.2102525    0.05749442
27  FOXN3   Cardiomyocyte  0.1482747    0.02028319
28  PBX1    Cardiomyocyte  0.1256054    0.05625342
29  MGA     Cardiomyocyte  0.3404133    0.09697406
30  KLF3    Cardiomyocyte  0.4052965    0.11754096
⋮   ⋮       ⋮             ⋮            ⋮
180 BNC2    Pericyte      0.17789687   0.17316922
181 ETS1    Pericyte      0.18494454   0.12392718
182 MEIS1   Pericyte      0.19366346   0.01413755
183 KLF12   Pericyte      0.17743012   0.21206500
184 KDM5A   Pericyte      0.35146915   0.22121202
185 MLLT10  Pericyte      0.19228962   0.23174872
186 SMARCC1 Pericyte      0.16625187   0.20456872
187 IRF8    Pericyte      0.15756894   0.06576629
188 ETV6    Pericyte      0.15378750   0.22046618
189 NFIB    Pericyte      0.12034821   0.10064123
190 MAF     Pericyte      0.10188928   0.13121895
191 SP3     Pericyte      0.17878538   0.20122344
192 RARB    Pericyte      0.17382611   0.03868123
193 NFIA    Pericyte      0.10673809   0.17750177
194 ETV1    Pericyte      0.19118090   0.02031498
195 NR6A1   Pericyte      0.16344390   0.05421295
196 RCOR1   Pericyte      0.16175888   0.14908710
197 ADNP    Pericyte      0.09658153   0.23923046
198 FOXO1   Pericyte      0.08411987   0.22400573
199 RUNX1   Pericyte      0.07354808   0.16001036
200 ZNF33A  Pericyte      0.14224436   0.27375403
201 SOX5    Pericyte      0.07122930   0.15189075
202 MEIS2   Pericyte      0.08560387   0.04186193
203 NFATC2  Pericyte      0.05419662   0.21781342
204 UBE2K   Pericyte      0.05543151   0.23015475
205 SMAD3   Pericyte      0.07101499   0.11920172
206 SMAD2   Pericyte      0.06748471   0.25102697
207 MAFB    Pericyte      0.03367553   0.21517860
208 MEF2C   Pericyte      0.07075089   0.16557617
209 TFDP2   Pericyte      0.03674942   0.12216429

In [15]:
sig_shared_regulons_dir <- shared_regulons_dir %>%
  filter(abs(log2FC_fetal) > 0.5, abs(log2FC_disease) > 0.1)

In [23]:
df_long <- sig_shared_regulons_dir %>%
  pivot_longer(
    cols = starts_with("log2FC_"),
    names_to = "comparison",
    names_prefix = "log2FC_",
    values_to = "log2FC"
  )

df_long %>% head()

  regulon cell_type     comparison log2FC
1 TCF4    Cardiomyocyte fetal      0.6855273
2 TCF4    Cardiomyocyte disease    0.1044070
3 ZNF90   Cardiomyocyte fetal      2.1582879
4 ZNF90   Cardiomyocyte disease    0.4186961
5 ZNF846  Cardiomyocyte fetal      0.7189348
6 ZNF846  Cardiomyocyte disease    0.1749794

In [42]:
unique(df_long$regulon)

 [1] "TCF4"   "ZNF90"  "ZNF846" "PLAGL1" "NFIX"   "ZNF423" "JUNB"   "FOSB"
 [9] "PGR"    "AR"     "RUNX2"  "ZNF680" "MTA3"   "CEBPD"  "CREB5"  "NFE2L3"
[17] "SOX5"   "PDLIM5" "BACH2"  "KLF3"

In [41]:
options(repr.plot.width = 15, repr.plot.height = 6)

p1 <- ggplot(data = df_long, aes(x = comparison, y = regulon, size = log2FC, color = log2FC)) + 
    geom_point() +
    facet_wrap(~ cell_type, ncol = 5) +  
    scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) + 
    theme_bw() +
    theme(
        strip.background = element_blank(),  
        strip.text = element_text(size = 14, color = "black"),  # clean facet labels
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        axis.text.x = element_text(size = 12, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_text(size = 18, hjust = 0.5)
)

ggsave(p1, filename = "05_fetal_reactivation_TFs.pdf", width = 15, height = 6)