In [1]:
import pandas as pd
import numpy as np

### Identify fetalization genes that overlap with the DCM/HCM prioritized genes 

Use the genes prioritized using our method and the original papers

In [2]:
DCM_df = pd.read_csv("02B_prioritized_DCM_genes.csv", index_col = 0)
HCM_df = pd.read_csv("02B_prioritized_HCM_genes.csv", index_col = 0)

In [15]:
fetalization_gene_dir = "../../../../RNA/aggregated_analysis/v3_pseudobulked_analysis/intersection_analysis/fetalization_genes/"

In [23]:
cell_types = ["Cardiomyocyte", "Endocardial", "Endothelial", "Fibroblast", "LEC", "Lymphoid", 
              "Myeloid", "Neuronal", "Pericyte", "vSMC"]

fetalization_gene_list = list()

for cell_type in cell_types:
    print(cell_type)
    fetalization_CM_genes = pd.read_csv(fetalization_gene_dir + cell_type + "_up_fetalization_genes.csv")
    fetalization_CM_genes.columns = ['gene']
    fetalization_CM_genes['cell_type'] = cell_type
    fetalization_gene_list.append(fetalization_CM_genes)

fetalization_all_df = pd.concat(fetalization_gene_list, ignore_index=True)

Cardiomyocyte
Endocardial
Endothelial
Fibroblast
LEC
Lymphoid
Myeloid
Neuronal
Pericyte
vSMC

In [40]:
concordant_DCM_df = DCM_df[DCM_df['concordant'] == True]
concordant_HCM_df = HCM_df[HCM_df['concordant'] == True]

In [38]:
fetalization_all_df[fetalization_all_df['gene'].isin(concordant_DCM_df['current_study_predicted_gene'])]

         gene      cell_type
261      MELK  Cardiomyocyte
285       DTL  Cardiomyocyte
374   SLC28A1  Cardiomyocyte
524      SVIL    Endocardial
593     PROX1    Endocardial
670      MLF1    Endocardial
698     LAMB1    Endocardial
791     EPHB1    Endothelial
808   ADAMTS7    Endothelial
988     LAMB1    Endothelial
1040   PDZRN3     Fibroblast
1179    CRIM1     Fibroblast
1266    TANC1     Fibroblast
1748    MTSS1       Neuronal
2050    CRIM1           vSMC

In [42]:
fetalization_all_df[fetalization_all_df['gene'].isin(concordant_HCM_df['current_study_predicted_gene'])]

         gene      cell_type
183   SIPA1L1  Cardiomyocyte
240     RPLP0  Cardiomyocyte
374   SLC28A1  Cardiomyocyte
524      SVIL    Endocardial
537     PDE3A    Endocardial
583   SLCO1C1    Endocardial
593     PROX1    Endocardial
808   ADAMTS7    Endothelial
999    SLC1A4    Endothelial
1195     RGS6     Fibroblast
1748    MTSS1       Neuronal
2106  SIPA1L1           vSMC